# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e900065aff0f6649f04a8a71a34645846f18a553773ba139b6e5b520d0e75816ba5a13ec39abae08ecbf8a6ad83df6b25de8d4201279910b1034f4f303d3f76

test:
  secret_key_base: 49f3abdebef8f94642d0ea08c9e4494ee93c524fd05fad1e89029da16037ec7156c83acfac4a04469cc47e9439030b0751e6495d07c7fff4d7c5d58de6b3a7be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
